### PR TITLE
Update rspec, and add southern hemisphere

### PR DESCRIPTION
**Pull request by Br3nda**
I need to work out seasons for anywhere on the planet, but it doesn't need to be massively accurate.
I've taken your work for London and swapped the seasons (pushed date by 6months) to let the seasons work for northern or southern hemispheres.

I also ran rubocop over the code and upgraded to new rspec syntax.

### CODE REVIEW

**Comment by julescopeland** [comment]
Hey,

Thanks for this. I'd completely forgotten I'd written this gem 😂

Can you make the `hemisphere` argument default to `:northern`, either through an argument default, or even better, through a config setting.

This way, you're not breaking the interface, and don't need a major version bump.

**Comment by Br3nda** [comment]
I thought about that - but it seems like an anti-feature. Defaulting to anywhere results in coders not thinking about the fact you need a location to work out seasons. You end up with apps that assume everyone is having the same seasons.
I'd love to convince you that hemisphere needs to be explicitly set by the caller.

**Comment by julescopeland** [comment]
Hmm - I take your point, but the data is set up to give you the accurate season for London (for a given set of years).

If you could generalise the gem to provide data for all locations then your argument would be valid. (And please do - if you have the time 😄 )

Although... thinking about it - in order to provide data for _any_ location, you would need to know the latitude, which itself would infer the hemisphere...

It's a tricky one - I'm trying to consider all use cases. I would imagine that a lot of users will only be using it for a single country (or continent), and having to add extra arguments every time they call the method will get annoying (not to mention breaking existing code).

I guess I'd be happy with a combination approach...

Allow users to set a default in a config setting _if they choose to_ - then the logic will go something like:
```ruby
def season(hemisphere=nil)
  hemisphere = hemisphere || RubySeasons.config.default_hemisphere || raise ArgumentError.new("You need to pass the hemisphere (either :north or :south), or set the default by ...")
  #...
end
```

**Comment by Br3nda** [comment]
I'm using it on a website growstuff.org. A user could come from anywhere.

How about it as a default of north, but with a warning?

**Pull request closed without merging**
